#!/bin/bash
# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------
HOSTNAME="localhost"
VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[')
CLASS_PATH="./target/api-orders-$VERSION.jar"
# -----------------------------------------------------------------------------
#
#
#
# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
mvn clean install -q

java -cp $CLASS_PATH -server \
    -Dserver.address=$HOSTNAME \
    com.navent.api.orders.App
# -----------------------------------------------------------------------------
